<a href="https://colab.research.google.com/github/Vipanshi-gthb/HCL_proj/blob/feature%2Fdataset-exploration/P123_dataset_exp_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("P123_sample_ecommerce_dataset.csv")

In [3]:
df

,Order_ID,Order_Date,Customer_ID,Region,City,Category,Product,Unit_Price_INR,Quantity,Discount_Rate,Discount_Amount_INR,Total_Sales_INR,Unit_Cost_INR,Profit_INR,Payment_Method,Sales_Channel,Order_Status,Shipping_Days,Rating
0,ORD-100001,2026-07-10,CUST-1111,West,Ahmedabad,Electronics,Power Bank,1299,2,0.20,519.60,2078.40,1056.63,-34.86,Net Banking,Marketplace,Delivered,2,3.0
1,ORD-100002,2026-02-19,CUST-1097,North,Chandigarh,Beauty,Moisturizer,749,2,0.10,149.80,1348.20,578.34,191.52,Debit Card,Mobile App,Delivered,7,4.5
2,ORD-100003,2026-08-14,CUST-1106,North,Jaipur,Fashion,Backpack,1999,4,0.00,0.00,7996.00,1508.61,1961.56,Credit Card,Website,Returned,2,4.0
3,ORD-100004,2026-04-10,CUST-1007,Central,Kanpur,Books,Fiction Bestseller,599,3,0.15,269.55,1527.45,354.40,464.25,Net Banking,Marketplace,Delivered,4,4.0
4,ORD-100005,2026-04-12,CUST-1070,South,Coimbatore,Books,Business Strategy,899,1,0.05,44.95,854.05,540.44,313.61,UPI,Marketplace,Returned,1,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD-100496,2026-04-30,CUST-1114,North,Delhi,Home & Kitchen,Electric Kettle,1599,3,0.15,719.55,4077.45,1030.57,985.74,Credit Card,Mobile App,Delivered,1,4.5
496,ORD-100497,2026-02-27,CUST-1115,East,Guwahati,Home & Kitchen,Coffee Maker,4299,3,0.05,644.85,12252.15,2600.25,4451.40,Credit Card,Marketplace,Returned,7,3.5
497,ORD-100498,2026-05-27,CUST-1032,North,Chandigarh,Electronics,Smart Watch,3499,1,0.15,524.85,2974.15,2782.59,191.56,Debit Card,Marketplace,Returned,1,3.5
498,ORD-100499,2026-02-27,CUST-1017,South,Chennai,Home & Kitchen,Electric Kettle,1599,1,0.10,159.90,1439.10,1043.51,395.59,Debit Card,Marketplace,Delivered,3,3.0
499,ORD-100500,2026-09-10,CUST-1132,West,Surat,Home & Kitchen,Storage Organizer,899,1,0.00,0.00,899.00,572.62,326.38,Cash on Delivery,Mobile App,Delivered,6,4.5

In [4]:
df.head()

,Order_ID,Order_Date,Customer_ID,Region,City,Category,Product,Unit_Price_INR,Quantity,Discount_Rate,Discount_Amount_INR,Total_Sales_INR,Unit_Cost_INR,Profit_INR,Payment_Method,Sales_Channel,Order_Status,Shipping_Days,Rating
0,ORD-100001,2026-07-10,CUST-1111,West,Ahmedabad,Electronics,Power Bank,1299,2,0.20,519.60,2078.40,1056.63,-34.86,Net Banking,Marketplace,Delivered,2,3.0
1,ORD-100002,2026-02-19,CUST-1097,North,Chandigarh,Beauty,Moisturizer,749,2,0.10,149.80,1348.20,578.34,191.52,Debit Card,Mobile App,Delivered,7,4.5
2,ORD-100003,2026-08-14,CUST-1106,North,Jaipur,Fashion,Backpack,1999,4,0.00,0.00,7996.00,1508.61,1961.56,Credit Card,Website,Returned,2,4.0
3,ORD-100004,2026-04-10,CUST-1007,Central,Kanpur,Books,Fiction Bestseller,599,3,0.15,269.55,1527.45,354.40,464.25,Net Banking,Marketplace,Delivered,4,4.0
4,ORD-100005,2026-04-12,CUST-1070,South,Coimbatore,Books,Business Strategy,899,1,0.05,44.95,854.05,540.44,313.61,UPI,Marketplace,Returned,1,4.0

In [5]:
df.tail()

,Order_ID,Order_Date,Customer_ID,Region,City,Category,Product,Unit_Price_INR,Quantity,Discount_Rate,Discount_Amount_INR,Total_Sales_INR,Unit_Cost_INR,Profit_INR,Payment_Method,Sales_Channel,Order_Status,Shipping_Days,Rating
495,ORD-100496,2026-04-30,CUST-1114,North,Delhi,Home & Kitchen,Electric Kettle,1599,3,0.15,719.55,4077.45,1030.57,985.74,Credit Card,Mobile App,Delivered,1,4.5
496,ORD-100497,2026-02-27,CUST-1115,East,Guwahati,Home & Kitchen,Coffee Maker,4299,3,0.05,644.85,12252.15,2600.25,4451.40,Credit Card,Marketplace,Returned,7,3.5
497,ORD-100498,2026-05-27,CUST-1032,North,Chandigarh,Electronics,Smart Watch,3499,1,0.15,524.85,2974.15,2782.59,191.56,Debit Card,Marketplace,Returned,1,3.5
498,ORD-100499,2026-02-27,CUST-1017,South,Chennai,Home & Kitchen,Electric Kettle,1599,1,0.10,159.90,1439.10,1043.51,395.59,Debit Card,Marketplace,Delivered,3,3.0
499,ORD-100500,2026-09-10,CUST-1132,West,Surat,Home & Kitchen,Storage Organizer,899,1,0.00,0.00,899.00,572.62,326.38,Cash on Delivery,Mobile App,Delivered,6,4.5

In [6]:
df.shape

(500, 19)

In [7]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Region', 'City', 'Category',
       'Product', 'Unit_Price_INR', 'Quantity', 'Discount_Rate',
       'Discount_Amount_INR', 'Total_Sales_INR', 'Unit_Cost_INR', 'Profit_INR',
       'Payment_Method', 'Sales_Channel', 'Order_Status', 'Shipping_Days',
       'Rating'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             500 non-null    object
 1   Order_Date           500 non-null    object
 2   Customer_ID          500 non-null    object
 3   Region               500 non-null    object
 4   City                 500 non-null    object
 5   Category             500 non-null    object
 6   Product              500 non-null    object
 7   Unit_Price_INR       500 non-null    int64
 8   Quantity             500 non-null    int64
 9   Discount_Rate        500 non-null    float64
 10  Discount_Amount_INR  500 non-null    float64
 11  Total_Sales_INR      500 non-null    float64
 12  Unit_Cost_INR        500 non-null    float64
 13  Profit_INR           500 non-null    float64
 14  Payment_Method       500 non-null    object
 15  Sales_Channel        500 non-null    object
 16  Order_Status         500 non-null    object
 17  Shipping_Days        500 non-null    int64
 18  Rating               428 non-null    float64
dtypes: float64(6), int64(3), object(10)
memory usage: 74.3+ KB

In [9]:
df.describe()

,Unit_Price_INR,Quantity,Discount_Rate,Discount_Amount_INR,Total_Sales_INR,Unit_Cost_INR,Profit_INR,Shipping_Days,Rating
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,428.000000
mean,1884.600000,2.080000,0.099700,372.411800,3578.508200,1293.489660,863.198720,3.380000,3.954439
std,1279.342047,1.093614,0.069819,492.219174,3426.469995,902.615981,1024.966866,2.319992,0.624184
min,599.000000,1.000000,0.000000,0.000000,479.200000,331.470000,-138.580000,0.000000,3.000000
25%,899.000000,1.000000,0.050000,73.650000,1328.100000,572.695000,242.652500,1.000000,3.500000
50%,1499.000000,2.000000,0.100000,212.325000,2558.400000,1027.715000,518.800000,3.000000,4.000000
75%,2499.000000,3.000000,0.150000,499.800000,4676.400000,1782.777500,1096.992500,5.000000,4.500000
max,5999.000000,4.000000,0.200000,3599.400000,23996.000000,4883.410000,10360.760000,7.000000,5.000000

In [10]:
df.isnull().sum()

Order_ID                0
Order_Date              0
Customer_ID             0
Region                  0
City                    0
Category                0
Product                 0
Unit_Price_INR          0
Quantity                0
Discount_Rate           0
Discount_Amount_INR     0
Total_Sales_INR         0
Unit_Cost_INR           0
Profit_INR              0
Payment_Method          0
Sales_Channel           0
Order_Status            0
Shipping_Days           0
Rating                 72
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [13]:
df.dtypes

Order_ID                       object
Order_Date             datetime64[ns]
Customer_ID                    object
Region                         object
City                           object
Category                       object
Product                        object
Unit_Price_INR                  int64
Quantity                        int64
Discount_Rate                 float64
Discount_Amount_INR           float64
Total_Sales_INR               float64
Unit_Cost_INR                 float64
Profit_INR                    float64
Payment_Method                 object
Sales_Channel                  object
Order_Status                   object
Shipping_Days                   int64
Rating                        float64
dtype: object

In [14]:
df["Category"].unique()

array(['Electronics', 'Beauty', 'Fashion', 'Books', 'Home & Kitchen'],
      dtype=object)

In [15]:
df["Region"].unique()

array(['West', 'North', 'Central', 'South', 'East'], dtype=object)

In [16]:
df["Order_Status"].unique()

array(['Delivered', 'Returned', 'Cancelled'], dtype=object)

In [17]:
df["Payment_Method"].unique()

array(['Net Banking', 'Debit Card', 'Credit Card', 'UPI',
       'Cash on Delivery'], dtype=object)

In [18]:
df["Sales_Channel"].unique()

array(['Marketplace', 'Mobile App', 'Website'], dtype=object)

In [19]:
df["Category"].value_counts()

Category
Fashion           108
Home & Kitchen    108
Beauty            102
Books              94
Electronics        88
Name: count, dtype: int64

In [20]:
df["Region"].value_counts()

Region
East       113
South      111
North      102
West        98
Central     76
Name: count, dtype: int64

In [21]:
df["Order_Status"].value_counts()

Order_Status
Delivered    341
Returned      87
Cancelled     72
Name: count, dtype: int64

In [ ]:
# P_123 Dataset Exploration

## Dataset
Synthetic e-commerce sales dataset.

## Size
500 rows × 19 columns

## Data Types
- Numerical
- Categorical
- Date
- Identifier

## Main Business Information
- Orders
- Customers
- Products
- Sales
- Profit
- Discounts
- Regions
- Sales channels
- Payment methods
- Order status
- Ratings
- Shipping time

## Initial Observations
- The dataset contains e-commerce transaction-level data.
- Each row represents an order.
- Sales and profit can be analysed.
- Data can be grouped by category, product, region, city, etc.
- Time-based analysis can be performed using Order_Date.