<a href="https://colab.research.google.com/github/Vipanshi-gthb/HCL_proj/blob/feature%2Fdataset-analysis/P123_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("P123_sample_ecommerce_dataset.csv")

In [ ]:
df.head()

,Order_ID,Order_Date,Customer_ID,Region,City,Category,Product,Unit_Price_INR,Quantity,Discount_Rate,Discount_Amount_INR,Total_Sales_INR,Unit_Cost_INR,Profit_INR,Payment_Method,Sales_Channel,Order_Status,Shipping_Days,Rating
0,ORD-100001,2026-07-10,CUST-1111,West,Ahmedabad,Electronics,Power Bank,1299,2,0.20,519.60,2078.40,1056.63,-34.86,Net Banking,Marketplace,Delivered,2,3.0
1,ORD-100002,2026-02-19,CUST-1097,North,Chandigarh,Beauty,Moisturizer,749,2,0.10,149.80,1348.20,578.34,191.52,Debit Card,Mobile App,Delivered,7,4.5
2,ORD-100003,2026-08-14,CUST-1106,North,Jaipur,Fashion,Backpack,1999,4,0.00,0.00,7996.00,1508.61,1961.56,Credit Card,Website,Returned,2,4.0
3,ORD-100004,2026-04-10,CUST-1007,Central,Kanpur,Books,Fiction Bestseller,599,3,0.15,269.55,1527.45,354.40,464.25,Net Banking,Marketplace,Delivered,4,4.0
4,ORD-100005,2026-04-12,CUST-1070,South,Coimbatore,Books,Business Strategy,899,1,0.05,44.95,854.05,540.44,313.61,UPI,Marketplace,Returned,1,4.0

In [ ]:
df["Total_Sales_INR"].sum()

np.float64(1789254.1)

In [ ]:
def get_dataset_summary(df):
    return {
        "rows": len(df),
        "columns": len(df.columns),
        "column_names": list(df.columns),
        "missing_values": df.isnull().sum().to_dict(),
        "duplicate_rows": int(df.duplicated().sum())
    }

In [ ]:
summary = get_dataset_summary(df)
summary

In [ ]:
def calculate_sum(df, column):
    return df[column].sum()

In [ ]:
calculate_sum(df, "Total_Sales_INR")

np.float64(1789254.1)

In [ ]:
def calculate_average(df, column):
    return df[column].mean()

In [ ]:
calculate_average(df, "Profit_INR")

np.float64(863.19872)

In [ ]:
def calculate_min(df, column):
    return df[column].min()

In [ ]:
def calculate_max(df, column):
    return df[column].max()

In [ ]:
def sales_by_category(df):
    return (
        df.groupby("Category")["Total_Sales_INR"]
        .sum()
        .sort_values(ascending=False)
    )

In [ ]:
sales_by_category(df)

Category
Home & Kitchen    640692.85
Fashion           440716.70
Electronics       382096.30
Beauty            186398.40
Books             139349.85
Name: Total_Sales_INR, dtype: float64

In [ ]:
def sales_by_region(df):
    return (
        df.groupby("Region")["Total_Sales_INR"]
        .sum()
        .sort_values(ascending=False)
    )

In [ ]:
sales_by_region(df)

Region
East       490623.20
North      356305.40
West       343656.65
South      341669.00
Central    256999.85
Name: Total_Sales_INR, dtype: float64

In [ ]:
def profit_by_category(df):
    return (
        df.groupby("Category")["Profit_INR"]
        .sum()
        .sort_values(ascending=False)
    )

In [ ]:
def average_rating_by_category(df):
    return (
        df.groupby("Category")["Rating"]
        .mean()
        .sort_values(ascending=False)
    )

In [ ]:
def orders_by_status(df):
    return df["Order_Status"].value_counts()

In [ ]:
orders_by_status(df)

Order_Status
Delivered    341
Returned      87
Cancelled     72
Name: count, dtype: int64

In [ ]:
def monthly_sales(df):
    monthly = (
        df.groupby(df["Order_Date"].dt.to_period("M"))["Total_Sales_INR"]
        .sum()
    )

    return monthly

In [ ]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [ ]:
df["Order_Date"].dtype

dtype('<M8[ns]')

In [ ]:
monthly_sales(df)

Order_Date
2026-01    172517.15
2026-02    252520.95
2026-03    206141.40
2026-04    216539.45
2026-05    265162.70
2026-06    131364.05
2026-07     97673.30
2026-08    259441.55
2026-09    187893.55
Freq: M, Name: Total_Sales_INR, dtype: float64

In [ ]:
def best_selling_product(df):
    return (
        df.groupby("Product")["Quantity"]
        .sum()
        .sort_values(ascending=False)
        .head(1)
    )

In [ ]:
best_selling_product(df)

Product
Casual Shirt    67
Name: Quantity, dtype: int64

In [ ]:
def highest_revenue_product(df):
    return (
        df.groupby("Product")["Total_Sales_INR"]
        .sum()
        .sort_values(ascending=False)
        .head(1)
    )

In [ ]:
def analyze(df, operation, column=None):

    if operation == "sum":
        return calculate_sum(df, column)

    elif operation == "average":
        return calculate_average(df, column)

    elif operation == "min":
        return calculate_min(df, column)

    elif operation == "max":
        return calculate_max(df, column)

    elif operation == "sales_by_category":
        return sales_by_category(df)

    elif operation == "sales_by_region":
        return sales_by_region(df)

    elif operation == "profit_by_category":
        return profit_by_category(df)

    elif operation == "monthly_sales":
        return monthly_sales(df)

    elif operation == "orders_by_status":
        return orders_by_status(df)

    elif operation == "best_selling_product":
        return best_selling_product(df)

    elif operation == "highest_revenue_product":
        return highest_revenue_product(df)

    else:
        return "Unknown operation"

In [ ]:
analyze(df, "sum", "Total_Sales_INR")

np.float64(1789254.1)

In [ ]:
analyze(df, "sales_by_category")

Category
Home & Kitchen    640692.85
Fashion           440716.70
Electronics       382096.30
Beauty            186398.40
Books             139349.85
Name: Total_Sales_INR, dtype: float64

In [ ]:
analyze(df, "monthly_sales")

Order_Date
2026-01    172517.15
2026-02    252520.95
2026-03    206141.40
2026-04    216539.45
2026-05    265162.70
2026-06    131364.05
2026-07     97673.30
2026-08    259441.55
2026-09    187893.55
Freq: M, Name: Total_Sales_INR, dtype: float64